리뷰 글쓰기 기능 작성
wecode-bootcamp-korea/33-1st-crowsSeven-backend pull request #14
Opened 2022-05-29 14:52 UTC by onlining

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [v] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
글쓰기 기능 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰 글쓰기 기능 구현2. 
<br />
-한 소비자가 구매한 한개의 물품에 관해서는 리뷰를 한번 밖에 쓸 수 없도록 필터링

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-05-30 01:30 UTC, bigfanoftim requested changes

2022-05-30 01:30 UTC, bigfanoftim commented on reviews/urls.py
> +    path("/write", ReviewView.as_view()),
이미 POST Method에 의미가 충분히 담겨져 있다고 봅니다. 또한 여러 방식으로 고민해볼 수 있겠네요.
```python
#### Good ####
# parameter로 product_id를 넘기지 않고 body에 product_id를 넘기는 경우
POST :8000/reviews

# reviews앱을 따로 관리하며 1번 product에 review
POST :8000/reviews/product/1

# products앱에 review까지 관리하며 1번 product에 review
POST :8000/products/1/review

#### Bad ####
POST :8000/reviews/write
```
```suggestion
```

2022-05-30 01:30 UTC, bigfanoftim commented on reviews/views.py
> +from users.utils        import jwt_expression
merge된 데코레이터 이름으로 수정해주세요.
```suggestion
```

2022-05-30 01:30 UTC, bigfanoftim commented on reviews/views.py
> +            user     = User.objects.get(id=request.user)
```suggestion
```

2022-05-30 01:30 UTC, bigfanoftim commented on reviews/views.py
> +            product  = Product.objects.get(name=product)
`product_id`를 전달받아 주세요.
```suggestion
```

2022-05-30 01:30 UTC, bigfanoftim commented on reviews/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status=200)
레코드 생성 status code를 한 번 적용해보세요~

2022-05-30 01:30 UTC, bigfanoftim commented on reviews/views.py
> +                product    = product2
`product2`는 뭘까요?

2022-05-30 01:39 UTC, onlining commented on reviews/views.py
> +            user     = User.objects.get(id=request.user)
혹시 이부분은 어떤 수정사항일까요?

2022-05-30 01:44 UTC, onlining commented on reviews/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status=200)
네

2022-05-30 01:45 UTC, onlining commented on reviews/views.py
> +                product    = product2
수정했습니다.

2022-05-30 01:45 UTC, onlining commented on reviews/views.py
> +from users.utils        import jwt_expression
네

2022-05-30 01:47 UTC, onlining commented on reviews/views.py
> +            product  = Product.objects.get(name=product)
이부분은 질문하고 수정하겠습니다.

2022-05-30 01:56 UTC, onlining commented on reviews/views.py
> +            product  = Product.objects.get(name=product)
네

2022-05-31 01:27 UTC, bigfanoftim requested changes
민정님 지금까지 드린 피드백이 전혀 적용되지 않은 모습입니다. 리뷰 요청으로 라벨을 수정하기 전에 `Files changed`에 들어와 본인의 코드를 점검하세요.

2022-05-31 01:27 UTC, bigfanoftim commented on reviews/urls.py
> +    path("/<int:product_id>", ReviewView.as_view()),
지금 주소가 이렇게 작성될 것 같은데 이러면 review의 id 1번을 의미하는 것처럼 보입니다. 제가 전에 남긴 리뷰 제대로 반영해주세요.
```python
:8000/reviews/1
```

2022-05-31 01:27 UTC, bigfanoftim commented on reviews/views.py
> +            product_id = Product.objects.get(id = product)
민정님 PR에 리뷰 요청 라벨을 달기 전에 본인의 코드를 전체적으로 점검해주세요.

2022-05-31 01:27 UTC, bigfanoftim commented on reviews/views.py
> +            if Review.objects.filter(Q(product_id=product)&Q(user_id=user.id)).exists():
Q가 필요한 경우인가요?

2022-05-31 01:27 UTC, bigfanoftim commented on utils.py
> +            user         = User.objects.get(id = payload["id"]).id
id를 붙이는 이유가 뭔가요? 그리고 id를 붙일거면 변수명이 user가 맞나요?

2022-05-31 02:04 UTC, onlining commented on reviews/views.py
> +            if Review.objects.filter(Q(product_id=product)&Q(user_id=user.id)).exists():
2개이상이면 무조건 필요하다고 수정했습니다. &로 연결해서 인식이 안됐다고 생각했습니다. 수정했습니다.

2022-05-31 02:04 UTC, onlining commented on utils.py
> +            user         = User.objects.get(id = payload["id"]).id
수정했습니다.

2022-05-31 02:04 UTC, onlining commented on reviews/views.py
> +            product_id = Product.objects.get(id = product)
네

2022-05-31 02:04 UTC, onlining commented on reviews/urls.py
> +    path("/<int:product_id>", ReviewView.as_view()),
네

2022-05-31 09:51 UTC, bigfanoftim approved these changes
LGTM 👍

2022-05-31 09:51 UTC, merged