제품 상세페이지 API 구현
wecode-bootcamp-korea/33-1st-crowsSeven-backend pull request #7
Opened 2022-05-26 07:59 UTC by onlining

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [v] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
제품 상세페이지 구현
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 단일 제품, 옵션이 있는 제품을 구별하여 상세페이지 구현
2. 재고관리를 위해 옵션별 수량표현
3. 옵션이 추가되었을 경우를 대비해서 특정 옵션별로 딕셔너리로 관리

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
모델링을 통해 제품을 옵션별로 고려할 수 있음을 확인했으며 본 프로젝트의 모델링으로 생길 수 있는 문제점을 이해했습니다. 

<br />

## :: 기타 질문 및 특이 사항
함수 로직이 너무 길어서 리팩토링이 반드시 필요해 보입니다. 필수기능을 구현하고 리팩토링을 할 수 있는 방법을 고민해보겠습니다.

2022-05-26 08:24 UTC, bigfanoftim requested changes
변수명, 들여쓰기 컨벤션 모두 제각각입니다. 리팩토링이 문제가 아니라 코드를 다른 사람이 읽을 수 있게 작성하는 것이 먼저이고, 그 후에 리뷰를 받아야 합니다.

- 들여쓰기 4칸 통일
- 네이밍 영어로
- `for i in products` 가 아니라 `for product in products` 와 같이 명확하게 작성

2022-05-26 11:08 UTC, onlining commented
일단 option_products = OptionProduct.objects.filter(product_id=product_id)
에서 
For option_product in options_products로 값을 하나씩 가져와봤을때 
  option_product.shoe_size.size if option_product.shoe_size_id else None이 인식되지 않고 'NoneType' object has no attribute 'name’이라고 에러가 납니다. shell에 들어가서 option_products에 값을 찍었을때 <class 'NoneType'>
이라고 떠서 option_product.shoe_size.size if option_product.shoe_size_id else None을 option_product.shoe_size.size if option_product.shoe_size_id is not None else None 이나 option_product.shoe_size.size if type(option_product.shoe_size_id) !=None else None 등으로 해봐도 나오지 않습니다. 널값이면 이렇게 가져오는 것 자체가 불가능한 것 같다고 생각이 듭니다. 이 방법으로 값을 가져올 수 없다면 옵션별로 표현되어야 하는 수량을 어떻게 가지고 나올지 감이 오지 않습니다. 도움이 필요합니다.

2022-05-27 01:00 UTC, bigfanoftim requested changes
이렇게 작성했을때 통신 결과도 함께 PR 내용에 올려주세요!

2022-05-27 01:00 UTC, bigfanoftim commented on products/views.py
> +            option_existence = True
True는 따로 변수를 할당한 이유가 있나요?

2022-05-27 01:23 UTC, onlining commented on products/views.py
> +            option_existence = True
원래 option_existence는 추가하지 않았는데 프론트랑 이야기하면서 옵션 유무를 체크해서 보내달라고 하셔서 추가했습니다.

2022-05-27 01:28 UTC, onlining commented on products/views.py
> +            option_existence = True
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/96784345/170610218-d93fa682-bca2-454f-9421-69bede61ba0c.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/96784345/170610282-ac4536be-4ab9-4a98-a6cb-d2bcdeb34fe8.png">

2022-05-27 07:53 UTC, closed without merging